version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing Terraform..."
      - wget https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
      - unzip terraform_1.6.0_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version
      - echo "Initializing Terraform..."
      - terraform init
      - echo "Validating Terraform configuration..."
      - terraform validate

  build:
    commands:
      - echo "Running Terraform plan..."
      - terraform plan -out=tfplan
      - echo "Converting plan to JSON..."
      - terraform show -json tfplan > tfplan.json
      - echo "Build completed successfully!"

artifacts:
  files:
    - tfplan.json
  name: terraform-artifacts